# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            jtleek
tagline:          'Leek Group'
description:      'Find me online <a href="http://twitter.com/jtleek">@jtleek</a>, <a href="http://twitter.com/simplystats">@simplystats</a>, <a href="http://simplystatistics.org">Simply Statistics</a>, and <a href="https://github.com/jtleek">Github</a>.'
url:              http://jtleek.github.io

author:
  name:           'Jeff Leek'
  url:            https://twitter.com/jtleek

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/jtleek/jtleek.github.io